// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzxQqzw3eEyZBwlRbZRIAwRn3PPo66gU8',
    appId: '1:509474815476:web:11604ac88fe2534a018da1',
    messagingSenderId: '509474815476',
    projectId: 'steamy-book',
    authDomain: 'steamy-book.firebaseapp.com',
    storageBucket: 'steamy-book.firebasestorage.app',
    measurementId: 'G-LS1M88EDH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1qdWRNv6w4BKSk_yyB65mfuZbLiWuup4',
    appId: '1:509474815476:android:9c74b26fa94dc436018da1',
    messagingSenderId: '509474815476',
    projectId: 'steamy-book',
    storageBucket: 'steamy-book.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDTcgn476lVJ0w3NSOMSZnShhODpqf0Bw',
    appId: '1:509474815476:ios:2eb49bccc0b4eb2d018da1',
    messagingSenderId: '509474815476',
    projectId: 'steamy-book',
    storageBucket: 'steamy-book.firebasestorage.app',
    iosClientId: '509474815476-6h6j5s2go6grhm6jgaaubeiaqe09nvsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.steamyBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDTcgn476lVJ0w3NSOMSZnShhODpqf0Bw',
    appId: '1:509474815476:ios:2eb49bccc0b4eb2d018da1',
    messagingSenderId: '509474815476',
    projectId: 'steamy-book',
    storageBucket: 'steamy-book.firebasestorage.app',
    iosClientId: '509474815476-6h6j5s2go6grhm6jgaaubeiaqe09nvsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.steamyBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzxQqzw3eEyZBwlRbZRIAwRn3PPo66gU8',
    appId: '1:509474815476:web:405425922596a5a7018da1',
    messagingSenderId: '509474815476',
    projectId: 'steamy-book',
    authDomain: 'steamy-book.firebaseapp.com',
    storageBucket: 'steamy-book.firebasestorage.app',
    measurementId: 'G-16PMT990HJ',
  );
}
